bool isSubsequence(char * s, char * t){
    // Initialize two pointers i and j storing the last indices of both the strings...
        int i = strlen(s) , j = strlen(t);
        i-- , j--;
        // Iterate until either of them becomes zero...
        while(i >= 0 && j >= 0) {
            // Compare characters...
            if(s[i] == t[j])
                i-- , j--;
            else
                j--;
        }
        // If i (pointer of the first string) is greater than or equal to 0...
        // we have not been able to traverse the first string completely...
        // Hence, it is not a subsequence of the second...
        if(i >= 0)
            return false;
        return true;        // Otherwise, return true...
}